name: automated test
run-name: AT
on: push
jobs:
  app_test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "testing app.js"
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
            node-version: "22"
      - run: npm ci
      - run: npm test
